# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mst_users',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=50)),
                ('usr_email', models.CharField(max_length=50)),
                ('usr_deleted', models.CharField(max_length=1)),
                ('usr_enabled', models.CharField(max_length=1)),
                ('usr_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('usr_location', models.CharField(max_length=50)),
            ],
        ),
    ]
